### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by hannescam**

### CODE REVIEW

**Review by ToxicStoxm — COMMENTED** [review]
wontfix

**Review by ToxicStoxm — CHANGES_REQUESTED** [review]
📱

**Comment by hannescam** [comment]
no wont change

**Comment by hannescam** [comment]
(delete not allowed)

**Review by ToxicStoxm — DISMISSED** [review]
add extremly ToxicStoxm

**Comment by hannescam** [comment]
> 📱

should this be an iphone

**Pull request merged**
